name: Font Library
baseurl: /font-library
url: http://katydecorah.com
description: An open source project to tag and organize Google Fonts.
permalink: pretty
image:
github: https://github.com/katydecorah/font-library
contributing: https://github.com/katydecorah/font-library/blob/gh-pages/CONTRIBUTING.md

angular: 1.5.5
jquery: 2.2.3
underscore: 1.8.3

port: 4000
host: 127.0.0.1

exclude:
- Gemfile
- .scss-lint.yml
- .travis.yml
- LICENSE
- README.md
- node_modules
- package.json
- test
- CONTRIBUTING.md

sass:
  style: :compressed
